# Generated by Django 6.0.2 on 2026-02-23 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100, verbose_name='食物名称')),
                ('calories_per_100g', models.PositiveIntegerField(verbose_name='每100克卡路里')),
                ('unit', models.CharField(default='克', max_length=20, verbose_name='单位')),
            ],
            options={
                'verbose_name': '食物',
                'verbose_name_plural': '食物',
                'db_table': 'food',
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '食物分类',
                'verbose_name_plural': '食物分类',
                'db_table': 'food_category',
            },
        ),
        migrations.CreateModel(
            name='FoodRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='数量')),
                ('meal_type', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐'), ('snack', '零食')], max_length=10, verbose_name='餐次')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '饮食记录',
                'verbose_name_plural': '饮食记录',
                'db_table': 'food_record',
                'ordering': ['-record_date', '-id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='foodentry',
            name='tracker_foo_user_id_fac7c7_idx',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='tracker.foodcategory', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='foodrecord',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tracker.food', verbose_name='食物'),
        ),
        migrations.AddField(
            model_name='foodrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_records', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='user',
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['food_name'], name='food_food_na_983e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['category', 'food_name'], name='food_categor_dc80e5_idx'),
        ),
        migrations.AddIndex(
            model_name='foodrecord',
            index=models.Index(fields=['user', 'record_date'], name='food_record_user_id_6c0087_idx'),
        ),
        migrations.AddIndex(
            model_name='foodrecord',
            index=models.Index(fields=['user', 'record_date', 'meal_type'], name='food_record_user_id_5d7980_idx'),
        ),
        migrations.AddIndex(
            model_name='foodrecord',
            index=models.Index(fields=['record_date'], name='food_record_record__5be013_idx'),
        ),
        migrations.DeleteModel(
            name='FoodEntry',
        ),
    ]
