# Generated by Django 4.2.28 on 2026-03-02 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0002_food_foodcategory_foodrecord_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Food', 'verbose_name_plural': 'Foods'},
        ),
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name': 'Food Category', 'verbose_name_plural': 'Food Categories'},
        ),
        migrations.AlterModelOptions(
            name='foodrecord',
            options={'ordering': ['-record_date', '-id'], 'verbose_name': 'Food Record', 'verbose_name_plural': 'Food Records'},
        ),
        migrations.AlterField(
            model_name='food',
            name='calories_per_100g',
            field=models.PositiveIntegerField(verbose_name='Calories per 100g'),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='tracker.foodcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(max_length=100, verbose_name='Food Name'),
        ),
        migrations.AlterField(
            model_name='food',
            name='unit',
            field=models.CharField(default='g', max_length=20, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='category_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='foodrecord',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tracker.food', verbose_name='Food'),
        ),
        migrations.AlterField(
            model_name='foodrecord',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=10, verbose_name='Meal Type'),
        ),
        migrations.AlterField(
            model_name='foodrecord',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='foodrecord',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Quantity (g)'),
        ),
        migrations.AlterField(
            model_name='foodrecord',
            name='record_date',
            field=models.DateField(verbose_name='Record Date'),
        ),
        migrations.AlterField(
            model_name='foodrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_records', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
